general.import = [
    "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

opacity = 1.0
blur = false

decorations = "Buttonless"

[scrolling]
history = 100000

[font]
size = 16
normal.family = "MesloLGS Nerd Font Mono"
